classDiagram

    class GameController {
        -List~IPlayer~ _players
        +GameController(IPlayer)
    }

    class IPlayer {
        <<Interface>>
        +string Name
        +Color Color
    }

    class Player {
        +string Name
        +Color Color
        +Player(string, Color)
    }

    class Color {
        <<Enumeration>>
        BLUE
        RED
        GREEN
        YELLOW
    }

    class Board {

    }

    %% PlayerSection
    GameController --> Player : uses
    Player ..|> IPlayer : realization
    Player --> Color : uses

    