classDiagram
    
    class GameController {
        -List~Player~ _players
        +SelectPlayer(Player)
    }

    class IPlayer {
        <<interface>>
        +string Name
        +Color Color
    }

    class Player {
        +string Name
        +Color Color
        +Player(string, Color)
    }

    class Color {
        <<enumeration>>
        +Blue
        +Red
        +Green
        +Yellow
    }

    %% PlayerSection
    GameController --> Player : uses
    Player ..|> IPlayer
    Player --> Color : uses

