// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Store.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20250812090709_Service")]
    partial class Service
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Beras Sania 5kg",
                            Price = 68000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Name = "Minyak Goreng Bimoli 2L",
                            Price = 35000m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 3,
                            Name = "Indomie Goreng",
                            Price = 3000m,
                            Stock = 500
                        },
                        new
                        {
                            Id = 4,
                            Name = "Telur Ayam 1kg",
                            Price = 27000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gula Pasir Gulaku 1kg",
                            Price = 16000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            Name = "Susu UHT Ultra Milk Coklat 1L",
                            Price = 18000m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kopi Kapal Api Special 165g",
                            Price = 15000m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 8,
                            Name = "Teh Celup Sariwangi",
                            Price = 8000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 9,
                            Name = "Saus Sambal ABC",
                            Price = 12000m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kecap Manis Bango",
                            Price = 22000m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 11,
                            Name = "Buku Tulis Sinar Dunia 38 Lbr",
                            Price = 5000m,
                            Stock = 250
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pensil 2B Faber-Castell",
                            Price = 3000m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pulpen Pilot G-2",
                            Price = 25000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 14,
                            Name = "Penghapus Staedtler",
                            Price = 4000m,
                            Stock = 180
                        },
                        new
                        {
                            Id = 15,
                            Name = "Kertas HVS A4 70gr Rim",
                            Price = 55000m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 16,
                            Name = "Stabilo Boss Original",
                            Price = 11000m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 17,
                            Name = "Tipe-X Cair Kenko",
                            Price = 7000m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sabun Mandi Lifebuoy",
                            Price = 4500m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 19,
                            Name = "Shampo Pantene Anti Dandruff",
                            Price = 28000m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 20,
                            Name = "Pasta Gigi Pepsodent",
                            Price = 13000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 21,
                            Name = "Deterjen Rinso Anti Noda 1.8kg",
                            Price = 45000m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 22,
                            Name = "Pewangi Pakaian Molto",
                            Price = 15000m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 23,
                            Name = "Pembersih Lantai Super Pell",
                            Price = 14000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 24,
                            Name = "Sabun Cuci Piring Sunlight",
                            Price = 17000m,
                            Stock = 130
                        },
                        new
                        {
                            Id = 25,
                            Name = "Tisu Wajah Paseo",
                            Price = 19000m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 26,
                            Name = "Pengharum Ruangan Glade",
                            Price = 25000m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 27,
                            Name = "Lampu LED Philips 10W",
                            Price = 30000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 28,
                            Name = "Baterai ABC Alkaline AA",
                            Price = 15000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 29,
                            Name = "Kabel USB-C Anker Powerline",
                            Price = 150000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 30,
                            Name = "Mouse Logitech M185",
                            Price = 180000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 31,
                            Name = "Headset Rexus F22",
                            Price = 120000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 32,
                            Name = "Stop Kontak Uticon 4 Lubang",
                            Price = 65000m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 33,
                            Name = "Coca-Cola Kaleng",
                            Price = 7000m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 34,
                            Name = "Air Mineral Aqua 600ml",
                            Price = 3500m,
                            Stock = 400
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chitato Sapi Panggang",
                            Price = 11000m,
                            Stock = 250
                        },
                        new
                        {
                            Id = 36,
                            Name = "Oreo Original",
                            Price = 9000m,
                            Stock = 180
                        },
                        new
                        {
                            Id = 37,
                            Name = "Silverqueen Cashew",
                            Price = 14000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 38,
                            Name = "Pocari Sweat 500ml",
                            Price = 8000m,
                            Stock = 220
                        },
                        new
                        {
                            Id = 39,
                            Name = "Masker Medis Sensi",
                            Price = 25000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 40,
                            Name = "Hand Sanitizer Dettol",
                            Price = 20000m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 41,
                            Name = "Tolak Angin Cair Sido Muncul",
                            Price = 4000m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 42,
                            Name = "Vitamin C IPI",
                            Price = 10000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 43,
                            Name = "Plester Hansaplast",
                            Price = 8000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 44,
                            Name = "Payung Lipat",
                            Price = 75000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 45,
                            Name = "Jas Hujan Axio",
                            Price = 250000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 46,
                            Name = "Sandal Jepit Swallow",
                            Price = 15000m,
                            Stock = 180
                        },
                        new
                        {
                            Id = 47,
                            Name = "Gembok Solid",
                            Price = 50000m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 48,
                            Name = "Lem Super Glue Alteco",
                            Price = 7000m,
                            Stock = 140
                        },
                        new
                        {
                            Id = 49,
                            Name = "Korek Api Gas",
                            Price = 3000m,
                            Stock = 400
                        },
                        new
                        {
                            Id = 50,
                            Name = "Gas LPG 3kg",
                            Price = 22000m,
                            Stock = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
